# Generated by Django 3.2.4 on 2023-06-06 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('speech', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='speechfile',
            old_name='uploaded_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='emotion',
            name='emotion_label',
        ),
        migrations.RemoveField(
            model_name='emotion',
            name='speech_file',
        ),
        migrations.AddField(
            model_name='emotion',
            name='label',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='speechfile',
            name='emotion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='speech.emotion'),
        ),
        migrations.AddField(
            model_name='speechfile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='speechfile',
            name='file',
            field=models.FileField(upload_to='speech_files'),
        ),
    ]
