# Generated by Django 3.2.4 on 2023-06-06 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speech', '0002_auto_20230606_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speechfile',
            name='emotion',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.DeleteModel(
            name='Emotion',
        ),
    ]
